spring:
    profiles:
        active: local
    datasource:
        hikari:
            pool-name: tilbox-pool
            minimum-idle: 5
            maximum-pool-size: 50
            connection-timeout: 3000
            idle-timeout: 600000
            max-lifetime: 1800000
            transaction-isolation: TRANSACTION_READ_COMMITTED
    jpa:
        generate-ddl: true
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                show_sql: true
                use_sql_comments: true
    flyway:
        enabled: false
    h2:
        console:
            enabled: true
            path: /h2-console

springfox:
    documentation:
        swagger-ui:
            base-url: /documentation
