name: "Chromatic Deployment"

on:
  pull_request:
    paths:
      - client/**
    branches:
      - '**'

jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: client
          exitZeroOnChanges: true
          allowConsoleErrors: true
          buildScriptName: "build:storybook"
        env:
          CHROMATIC_STORYBOOK_VERSION: react@6.0.28