name: "Chromatic Deployment"

on:
  pull_request:
    paths:
      - client/**
    branches:
      - '**'

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v1

      - name: yarn install
        run: yarn install

      - name: run chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: client
