name: Client deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Check Node v
        run: node -v

      - name: yarn install
        run: yarn install

      - name: Check lint
        run: yarn lint

      - name: Generate Environment Variables File for Production
        run: |
          echo "API_HOSTNAME=$API_HOSTNAME" >> .env.production
          echo "API_PORT=$API_PORT" >> .env.production
          echo "API_VERSION=$API_VERSION" >> .env.production
          echo "API_HOST=$API_HOST" >> .env.production
          cp .env.production .env.test
        env:
          API_HOSTNAME: ${{ secrets.API_HOSTNAME }}
          API_PORT: ${{ secrets.API_PORT }}
          API_VERSION: ${{ secrets.API_VERSION }}
          API_HOST: ${{ secrets.API_HOST }}

      - name: Check test coverage
        run: yarn test:coverage

      - name: Build
        run: yarn build
